<?php

namespace App\Services;

use App\Models\Device;
use App\Models\Reading;
use App\Models\Warehouse;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class AlertMailService
{
    public function sendFromReading(
        Reading $reading,
        string $alertType,
        string $message,
        string $recipient
    ): bool {
        try {
            $warehouse = Warehouse::with('region')
                ->where('warehouse_code', $reading->warehouse_code)
                ->first();

            $regionName = $warehouse?->region?->region_name ?: $reading->region;
            $regionCode = $warehouse?->region?->region_code ?: $reading->region_code;

            $warehouseName = $warehouse?->warehouse_name ?: $reading->warehouse;
            $warehouseCode = $warehouse?->warehouse_code ?: $reading->warehouse_code;

            $deviceName = $reading->device_name;
            $sensorDeviceId = $reading->sensor_device_id;
            $deviceLine = $deviceName
                ? $deviceName . ' (' . $sensorDeviceId . ')'
                : $sensorDeviceId;

            $recordedAt = $reading->recorded_at
                ? $reading->recorded_at->format('d M Y H:i')
                : now()->format('d M Y H:i');

            $alertTypeLabel = strtoupper($alertType);

            $mailBody =
                "==============================\n"
                . "ATS WAREHOUSE ALERT\n"
                . "==============================\n"
                . "ALERT TYPE : {$alertTypeLabel}\n"
                . "MESSAGE : {$message}\n"
                . "------------------------------\n"
                . "DEVICE : {$deviceLine}\n"
                . "DEVICE IP : " . ($reading->device_ip ?? '-') . "\n"
                . "DEVICE TYPE : " . ($reading->device_type ?? '-') . "\n"
                . "------------------------------\n"
                . "REGION : " . ($regionName ?? '-') . " (" . ($regionCode ?? '-') . ")\n"
                . "WAREHOUSE : " . ($warehouseName ?? '-') . " (" . ($warehouseCode ?? '-') . ")\n"
                . "GODOWN : " . ($reading->godown ?? '-') . "\n"
                . "COMPARTMENT: " . ($reading->compartment ?? '-') . "\n"
                . "------------------------------\n"
                . "READING : value=" . ($reading->reading_value ?? '-')
                . ", level=" . ($reading->level ?? '-')
                . ", status=" . ($reading->status ?? '-') . "\n"
                . "UNIT : " . ($reading->unit ?? '-') . "\n"
                . "RECORDED AT: {$recordedAt}\n"
                . "------------------------------\n"
                . "Generated by ATS Monitoring system Monitoring\n";

            $target = $warehouseName ?: 'Warehouse';

            Mail::raw(
                $mailBody,
                function ($m) use ($recipient, $alertTypeLabel, $target) {
                    $m->to($recipient)
                        ->subject('Warehouse Alert [' . $alertTypeLabel . ']: ' . $target);
                }
            );

            Log::info('Alert mail sent from reusable service', [
                'to' => $recipient,
                'reading_id' => $reading->id,
                'type' => $alertType,
            ]);

            return true;
        } catch (\Throwable $e) {
            Log::error('AlertMailService failed', [
                'error' => $e->getMessage(),
                'reading_id' => $reading->id ?? null,
            ]);

            return false;
        }
    }
}
