<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasColumn('warehouses', 'uuid')) {
            Schema::table('warehouses', function (Blueprint $table) {
                $table->uuid('uuid')->nullable()->unique()->after('id');
            });
        }

        // [external warehouse ID, external region ID, warehouse name]
        $warehouses = [
            ['53', '5', 'ABOHAR-I'],
            ['280', '10', 'ADILABAD'],
            ['281', '18', 'ADONI'],
            ['375', '16', 'AKOLA-I'],
            ['376', '16', 'AKOLA-II(PEG)'],
            ['377', '16', 'AMBERNATH-I'],
            ['1', '1', 'ANAND'],
            ['322', '13', 'ASKA(PEG)'],
            ['227', '6', 'ASSANDH'],
            ['350', '15', 'BAHRAICH'],
            ['27', '3', 'BALAGHAT(PEG)'],
            ['323', '13', 'BALASORE II'],
            ['324', '13', 'BALASORE(PEG)'],
            ['325', '13', 'BALJITPARA(PEG)'],
            ['351', '15', 'BALLIA'],
            ['352', '15', 'BANDA'],
            ['9', '2', 'BANG-I/APMC/YESHWANTPURA'],
            ['302', '11', 'BARAN'],
            ['326', '13', 'BARGARH-I'],
            ['228', '6', 'BARHI'],
            ['2', '1', 'BARODA-I'],
            ['353', '15', 'BASTI'],
            ['229', '5', 'BATHINDA (PEG)'],
            ['10', '2', 'BELGAUM'],
            ['327', '14', 'BERHAMPORE(PEG)'],
            ['328', '13', 'BERHAMPUR'],
            ['383', '17', 'BETTIAH(PEG)'],
            ['127', '15', 'BHADOHI'],
            ['303', '11', 'BHARATPUR'],
            ['44', '4', 'BHATAPARA-II'],
            ['45', '4', 'BHATAPARA-I (PEG)'],
            ['28', '3', 'BHIND(PEG)'],
            ['230', '5', 'BHOGPUR'],
            ['29', '3', 'BHOPAL-I'],
            ['233', '6', 'BIBIPUR (JIND)'],
            ['11', '2', 'BIDAR'],
            ['354', '15', 'BIJNORE'],
            ['304', '11', 'BIKANER-I'],
            ['305', '11', 'BIKANER-II'],
            ['46', '4', 'BILASPUR-I'],
            ['47', '4', 'BILASPUR-II(PEG)'],
            ['355', '15', 'BISALPUR'],
            ['282', '10', 'BODHAN(PEG)'],
            ['329', '13', 'BOLANGIR(PEG)'],
            ['30', '3', 'BURHANPUR-I'],
            ['231', '5', 'CHANALON'],
            ['356', '15', 'CHANDAUSI-I'],
            ['357', '15', 'CHANDAUSI-II'],
            ['330', '14', 'CHANDRAKONA ROAD(PEG)'],
            ['232', '6', 'CHARKHI DADRI'],
            ['31', '3', 'CHHINDWARA(PEG)'],
            ['260', '7', 'CHIDAMBARAM'],
            ['358', '15', 'CHIRGAON'],
            ['306', '11', 'CHOMU'],
            ['331', '13', 'CHOUDWAR'],
            ['261', '7', 'CUDDALORE(PEG)'],
            ['212', '17', 'DARBHANGA'],
            ['12', '2', 'DAVANGERE'],
            ['237', '6', 'DEHRA(PEG)'],
            ['307', '11', 'DEOLI'],
            ['48', '4', 'DHAMTARI'],
            ['13', '2', 'DHARWAD'],
            ['144', '9', 'DHUBRI'],
            ['277', '9', 'DIMAPUR'],
            ['234', '5', 'DRASS'],
            ['283', '18', 'DUGGIRALA'],
            ['359', '15', 'DUMARIAGANJ'],
            ['332', '14', 'DURGACHAK'],
            ['317', '12', 'EDATHALA,ALUVA'],
            ['360', '15', 'ETAWAH'],
            ['361', '15', 'FAIZABAD'],
            ['14', '2', 'GADAG-I'],
            ['15', '2', 'GADAG-II(PEG)'],
            ['284', '10', 'GADWAL(PEG)'],
            ['333', '14', 'GARDEN REACH'],
            ['238', '5', 'GARSHANKAR'],
            ['362', '15', 'GOLA GOKARNATH'],
            ['378', '16', 'GONDIA-II(PEG)'],
            ['285', '18', 'GUDIVADA'],
            ['16', '2', 'GULBARGA-I'],
            ['17', '2', 'GULBARGA-II'],
            ['71', '5', 'GURDASPUR'],
            ['308', '11', 'HANUMANGARH -I'],
            ['309', '11', 'HANUMANGARH -II'],
            ['363', '15', 'HARDOI(PEG)'],
            ['384', '17', 'HAZARIBAGH'],
            ['239', '6', 'HISSAR'],
            ['240', '5', 'HOSHIARPUR'],
            ['262', '7', 'HOSUR(PEG)'],
            ['18', '2', 'HUBLI'],
            ['241', '6', 'INDRI'],
            ['242', '6', 'JAGADHARI'],
            ['364', '15', 'JAHANGIRABAD-I'],
            ['365', '15', 'JAHANGIRABAD-II'],
            ['272', '8', 'JASPUR'],
            ['334', '13', 'JATNI(PEG)'],
            ['335', '13', 'JEYPORE'],
            ['310', '11', 'JHUNJHUNU'],
            ['278', '9', 'JORHAT-I'],
            ['336', '13', 'JUNAGARH(PEG)'],
            ['286', '18', 'KADAPA (Part-I)'],
            ['287', '18', 'KAIKALUR'],
            ['100', '6', 'KAITHAL'],
            ['288', '18', 'KAKINADA'],
            ['318', '12', 'KAKKANAD'],
            ['319', '12', 'KAKKANCHERRY'],
            ['337', '13', 'KALAMATI'],
            ['320', '12', 'KANJIKODE/PALLAKAD'],
            ['3', '1', 'KARACHIA'],
            ['289', '10', 'KARIMNAGAR-I'],
            ['243', '6', 'KARNAL-I'],
            ['244', '6', 'KARNAL-III'],
            ['273', '8', 'KASHIPUR-I'],
            ['274', '8', 'KASHIPUR-II'],
            ['217', '17', 'KATIHAR'],
            ['34', '3', 'KATNI'],
            ['339', '13', 'KENDUPALLI-II(PEG)'],
            ['338', '13', 'KENDUPALLI-I(PEG)'],
            ['218', '17', 'KHAGARIA(PEG)'],
            ['340', '14', 'KHARAGPUR(PEG)'],
            ['275', '8', 'KHATIMA'],
            ['341', '13', 'KOKSARA(PEG)'],
            ['311', '11', 'KOTPUTLI'],
            ['263', '7', 'KUMBAKONAM'],
            ['321', '12', 'KUNNAMTHANAM(PEG)'],
            ['245', '6', 'LADWA'],
            ['290', '18', 'MACHILIPATNAM'],
            ['220', '17', 'MADHEPURA'],
            ['264', '7', 'MADURAI-II'],
            ['35', '3', 'MAKSI(PEG)'],
            ['36', '3', 'MALANPUR'],
            ['342', '14', 'MALDA(PEG)'],
            ['246', '6', 'MANDI'],
            ['235', '6', 'MANDI ADAMPUR'],
            ['247', '5', 'MANDI GOBINDGARH(PEG)'],
            ['265', '7', 'MANNARGUDI'],
            ['248', '5', 'MANSA'],
            ['343', '13', 'MARSHAGHAI(PEG)'],
            ['366', '15', 'MAUNATH BHANJAN'],
            ['291', '10', 'MEHABOOBNAGAR'],
            ['379', '16', 'MIRAJ'],
            ['380', '16', 'MIRAJ BD'],
            ['80', '5', 'MOGA-I'],
            ['249', '5', 'MOGA-II(PEG)'],
            ['344', '14', 'MOGRA(GOARA)'],
            ['250', '5', 'MOHALI'],
            ['37', '3', 'MORENA-I'],
            ['38', '3', 'MORENA-II(PEG)'],
            ['221', '17', 'MUNGER'],
            ['367', '15', 'MUZAFFAR NAGAR BD'],
            ['368', '15', 'MUZAFFAR NAGAR-I'],
            ['345', '13', 'NABARANGPUR(PEG)'],
            ['83', '5', 'NABHA'],
            ['251', '5', 'NABHA BD'],
            ['4', '1', 'NADIAD'],
            ['266', '7', 'NAGERCOIL'],
            ['369', '15', 'NAINI(PEG)'],
            ['292', '18', 'NANDIKOTKUR'],
            ['293', '18', 'NANDYAL'],
            ['252', '6', 'NARAINGARH'],
            ['21', '2', 'NARGUND'],
            ['39', '3', 'NARSINGHPUR-I(PEG)'],
            ['253', '6', 'NARWANA'],
            ['294', '18', 'NIDAMANUR'],
            ['155', '10', 'NIZAMABAD'],
            ['156', '18', 'ONGOLE'],
            ['346', '14', 'PANIHATI'],
            ['295', '18', 'PEDAKAKANI'],
            ['50', '4', 'RAIGARH-I'],
            ['51', '4', 'RAIGARH-II(PEG)'],
            ['52', '4', 'RAIPUR-IV'],
            ['158', '18', 'RAJAHMUNDRY'],
            ['140', '15', 'RAMPUR'],
            ['370', '15', 'ROBERTSGANJ'],
            ['254', '5', 'ROPAR(PEG)'],
            ['371', '15', 'SAHARANPUR BD'],
            ['381', '16', 'SANGLI'],
            ['40', '3', 'SANWAR'],
            ['296', '10', 'SARANGPUR'],
            ['347', '14', 'SARGACHI(PEG)'],
            ['348', '14', 'SARUL'],
            ['22', '2', 'SEDAM'],
            ['372', '15', 'SHAHGANJ'],
            ['373', '15', 'SHAHJAHANPUR'],
            ['374', '15', 'SHAMLI'],
            ['41', '3', 'SHEOPURKALAN-I'],
            ['42', '3', 'SHEOPURKALAN-II(PEG)'],
            ['23', '2', 'SHIKARIPUR'],
            ['297', '10', 'SIDDIPET'],
            ['312', '11', 'SIKAR'],
            ['267', '7', 'SINGANALLUR ACC AND ICD'],
            ['255', '5', 'SIRHIND'],
            ['256', '6', 'SIRSA'],
            ['313', '11', 'SITAPURA-II'],
            ['43', '3', 'SOHAGPUR'],
            ['257', '6', 'SOLAN'],
            ['258', '6', 'SONEPAT'],
            ['349', '13', 'SONEPUR(PEG)'],
            ['279', '9', 'SORBHOG'],
            ['25', '2', 'SOUNDATTI'],
            ['314', '11', 'SRIGANGANAGAR-I'],
            ['315', '11', 'SRIGANGANAGAR-II'],
            ['316', '11', 'SRIMADHOPUR'],
            ['276', '8', 'SRI NAGAR(PEG)'],
            ['226', '17', 'SUPAUL'],
            ['298', '10', 'SURYAPET'],
            ['299', '18', 'TADEPALLIGUDEM'],
            ['268', '7', 'THANJAVUR'],
            ['269', '7', 'THOOTHUKUDI CFS'],
            ['259', '6', 'TOHANA(PEG)'],
            ['121', '7', 'TRICHY'],
            ['26', '2', 'TUMKUR/GUBBI'],
            ['270', '7', 'UDUMALPET'],
            ['300', '18', 'VADLAMUDI'],
            ['8', '1', 'VADOD'],
            ['301', '18', 'VIJAYWADA-II'],
            ['271', '7', 'VIRUDHUNAGAR(PEG)'],
            ['382', '16', 'YAVATMAL(PEG)'],
            ['236', '5', 'ZANSKAR'],
        ];

        foreach ($warehouses as [$warehouseUuid, $regionUuid, $warehouseName]) {
            $regionId = DB::table('regions')
                ->where('uuid', $regionUuid)
                ->value('id');

            if ($regionId === null) {
                continue;
            }

            // The local record includes the PEG suffix omitted by the source list.
            if ($warehouseName === 'RAIGARH-I') {
                $warehouseName = 'RAIGARH-I(PEG)';
            }

            DB::table('warehouses')
                ->where('warehouse_name', $warehouseName)
                ->update([
                    'uuid' => $warehouseUuid,
                    'region_id' => $regionId,
                ]);
        }
    }

    public function down(): void
    {
        if (Schema::hasColumn('warehouses', 'uuid')) {
            Schema::table('warehouses', function (Blueprint $table) {
                $table->dropUnique(['uuid']);
                $table->dropColumn('uuid');
            });
        }
    }
};
